name: run-tests

on:
  pull_request:
    branches: [main, dev]

jobs: 
   run-tests:
    name: Run Unit Test Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install Node Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm test
